version: 1
update_configs:
  - package_manager: "javascript"
    # where dependabot looks for package.json and lock file
    directory: "/"
    # opens pull requests as soon as a new package version is released
    update_schedule: "live"
    # bump the version in package.json as well as lock file
    version_requirement_updates: "increase_versions"